/*
 * This source file was generated by the Gradle 'init' task
 */
package br.dev.ferreiras;
import br.dev.ferreiras.virtual.CachedThreadedPool;
import br.dev.ferreiras.virtual.FixedThreadedPool;
import br.dev.ferreiras.virtual.VirtualThreadedPool;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        try {

            CachedThreadedPool cached = new CachedThreadedPool();
            cached.executeTasks(10_000);
            FixedThreadedPool fixed = new FixedThreadedPool();
            fixed.executeTasks(10_000);
            VirtualThreadedPool virtual = new VirtualThreadedPool();
            virtual.executeTasks(10_000);
        } catch (Exception ex) {
            LOGGER.error("Error... -> {}", ex.getMessage());
        }

        finally {

            LOGGER.info("End of Program... ");
        } 
    }
}
